{
    'name': 'MRP Workcenter Community Patch',
    'version': '1.0',
    'category': 'Manufacturing',
    'depends': ['mrp', 'hr'],
    'data': ['security/ir.model.access.csv',
             'views/mrp_workcenter.xml',
             'views/production.xml',
             'views/on_hand.xml',
             'views/res_set.xml',
             'views/product_template.xml',
             'views/mrp_bom.xml',
             'views/mrp_workorder.xml',
             'views/mrp_check.xml',
             # 'views/routing_center.xml',
             ],
    'installable': True,
    'auto_install': False,
}
