# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '16.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'PRAGATI BIOPHARMA PRIVATE LIMITED',
    'depends': [
        'account',
        'acs_invoice_summary',
        'base',
        'gft_inter_account',
        'hr',
        'l10n_in',
        'point_of_sale',
        'pragati_custom_module',
        'product',
        'uom',
        'web',

    ],
    'data': [
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
        'data/ir_ui_menu.xml',
    ],
    'application': False,

}
